<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="bhagyak" failures="1" tests="2" name="Testcase 3" time="0.023" errors="0" timestamp="2024-11-25T10:21:15 IST">
  <testcase classname="testngTestcases.Testcase3" name="doSkip" time="0.003">
    <skipped/>
  </testcase> <!-- doSkip -->
  <testcase classname="testngTestcases.Testcase3" name="userReg" time="0.002">
    <failure type="java.lang.AssertionError" message="Intentionally fails a testcase">
      <![CDATA[java.lang.AssertionError: Intentionally fails a testcase
at testngTestcases.Testcase3.userReg(Testcase3.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- userReg -->
</testsuite> <!-- Testcase 3 -->
